export const WALL_SPRITE_WIDTH_PX = 32;

export const ENEMY_MOVEMENT_SPEED = 0.015;
export const ENEMY_SPRITE_SIZE = 16;

export const TOWER_PROJECTILE_SPEED = 0.06;
export const TOWER_PROJECTILE_DAMAGE = 50;
export const TOWER_PROJECTILE_INTERVAL = 2000;
export const TOWER_PROJECTILE_INTERVAL_VARIANCE = 300;

export const PLAYER_SPEED = 0.06;

export const ATTACK_ANIM_DURATION = 200;
export const ATTACK_OFFSET_FROM_ENTITY = 10;
export const ENEMY_ATTACK_TIMEOUT = 500;
export const ENEMY_ATTACK_DELAY = 100;
